version: 2.1

orbs:
  # Use the orb-tools orb
  orb-tools: circleci/orb-tools@12.3.1
  # Use the shellcheck orb
  shellcheck: circleci/shellcheck@3.4.0
  # Use the node orb for running eslint
  node: circleci/node@7.1.0

# Pipeline parameters
parameters:
  # Whether to run integration tests
  run-integration-tests:
    type: boolean
    default: false
  # Orb publishing tag
  dev-orb-version:
    type: string
    default: dev:alpha
  # Orb name
  orb-name:
    type: string
    default: "nobari/wait-for"

# Define jobs
jobs:
  # Lint shell scripts in the orb
  shellcheck:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - shellcheck/install
      - shellcheck/check:
          dir: ./src
  
  # Lint YAML files with eslint
  eslint:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run eslint
          command: npm run lint:check

# Workflows
workflows:
  # Lint and validate the orb
  lint-pack:
    jobs:
      - shellcheck
      - eslint
      - orb-tools/lint:
          requires:
            - shellcheck
            - eslint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish:
          orb_name: << pipeline.parameters.orb-name >>
          vcs_type: github
          pub_type: dev
          dev_tags: << pipeline.parameters.dev-orb-version >>
          requires:
            - orb-tools/pack
          context: orb-publishing
          filters:
            branches:
              only: /^(main|master|dev)$/

  # When a tag is published, publish the orb
  tag-release:
    jobs:
      - eslint:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/
      - orb-tools/pack:
          requires:
            - eslint
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/
      - orb-tools/publish:
          orb_name: << pipeline.parameters.orb-name >>
          vcs_type: github
          pub_type: production
          requires:
            - orb-tools/pack
          context: orb-publishing
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/ 
